### ISSUE TITLE
Gainers/Losers doesn't appear to be showing the difference is fees.

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap-analytics#15]
It appears that gainers & losers aren't showing the difference in fees correctly when comparing 24h & 48h data.

https://analytics.sushiswap.fi/pairs/gainers
https://analytics.sushiswap.fi/pairs/losers

**Comment by 0xVoltron** [comment]
@matthewlilley can you elaborate more on this issue?

- how do I reproduce the issue?
- did anything change in the last month since this issue was created?
- how do you compare the 24h and 48h data?
- where do you see the difference and how do you know that it is not correct?

**Comment by matthewlilley** [comment]
Hey @0xVoltron!

I just had a look and it still doesn't seem right. I want to know the difference, so the difference in the number of fees, volume, etc... basically so I can see strong movements. It looks like I took a naive approach to this here:

https://github.com/sushiswap/sushiswap-analytics/blob/main/src/core/api/pages.js#L9

I expect you'd need to take into account 48 & 24 and get difference.
