### ISSUE TITLE
Query optimization

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap-analytics#17]
There are various opportunities to optimise queries to further increase performance.

I'd be keen to hear any ideas on this as well.

**Comment by 0xVoltron** [comment]
In this repo I was able to find only the GQL queries in `./core/queries`...

If that's the case, they are super basic fetch queries, which are written in a pretty clean and simple way.
I couldn't find any query that I would optimise at this point.

@matthewlilley Maybe I am missing something here?

**Comment by 0xVoltron** [comment]
I guess you are talking about the way we are using the queries in `./core/api`, right?
